[package]
name = "teia"
version = "0.1.0"
authors = ["Shotaro Tsuji <Shotaro.Tsuji@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
failure = "*"
structopt = "*"
botao = { git = "https://github.com/ShotaroTsuji/botao.git" }
